### ISSUE TITLE
make it available in bower registry again

### ISSUE THREAD

**Issue by waleedsamy** [Swimlane/angular-notifications#7]
why not put this version in bower registry again to make installtion more easily , you can upload with new registered bower name or connect with the @DerekRies to merge this fork with new tag , as i see main source not updated 2 years ago

**Comment by fetrarij** [comment]
+1

**Comment by waleedsamy** [comment]
until this pull request https://github.com/Swimlane/angular-notifications/pull/8 merged , you can install it with 

```
bower install angular-notifications-extended 
```

**Comment by Hypercubed** [comment]
I don't think bower support makes sense anymore.
